### ISSUE TITLE
3.0.8 => 3.0.10 Error: Could not find source map for: "...\validationHelper.ts"

### ISSUE THREAD

**Issue by baywet** [monounity/karma-typescript#245]
Hi,
We were blocked from upgrading to 3.0.9 because of this one https://github.com/monounity/karma-typescript/issues/226
I just tried upgrading to 3.0.10 and I'm getting a lot of errors like that.
```
Error: Could not find source map for: "...\subcontrols\peoplepicker\configuration\index.ts"
    at CoverageTransformer.addFileCoverage (...\node_modules\remap-istanbul\lib\CoverageTransformer.js:171:18)
    at ...\node_modules\remap-istanbul\lib\CoverageTransformer.js:298:14
    at Array.forEach (native)
    at CoverageTransformer.addCoverage (...\node_modules\remap-istanbul\lib\CoverageTransformer.js:296:24)
    at ...\node_modules\remap-istanbul\lib\remap.js:51:13
    at Array.forEach (native)
    at Reporter.remap (...\node_modules\remap-istanbul\lib\remap.js:50:16)
    at ...\node_modules\karma-typescript\dist\karma\reporter.js:38:42
    at Array.forEach (native)
    at Collection.forEach (...\node_modules\karma\lib\browser_collection.js:93:21)
    at Reporter.create.onRunComplete (...\node_modules\karma-typescript\dist\karma\reporter.js:26:26)
    at Server.<anonymous> (...\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:194:7)
    at emitRunCompleteIfAllBrowsersDone (...\node_modules\karma\lib\server.js:295:12)
    at Server.<anonymous> (...\node_modules\karma\lib\server.js:326:7)
```
[reporter.karma-typescript]: TypeError: Cannot read property 'text' of undefined

Might be relate to that https://github.com/monounity/karma-typescript/issues/240

**Comment by MrMosterd** [comment]
I get the same error when upgrading from 3.0.8 to 3.0.10.
I can reproduce it here: https://github.com/MrMosterd/bugreport1

**Comment by everedifice** [comment]
I have same issue. covered line are mismatched.

**Comment by cmercur2** [comment]
Confirming the same issue. 
Also an issue when tsconfig targets 'es5' - it appears to not be honored.

**Comment by erikbarke** [comment]
It works if I lock down `remap-istanbul` to v0.8.4 😞

**Comment by erikbarke** [comment]
The culprit is a regex in remap-istanbul that doesn't match the inline source maps from karma-typescript: https://github.com/SitePen/remap-istanbul/issues/149. I'll cut a panic release today with 'remap-istanbul@0.8.4'...

**Comment by erikbarke** [comment]
v3.0.11 is on npm now 😊

**Comment by rolandjitsu** [comment]
😄  now this is back:
```
30 01 2018 10:44:34.273:ERROR [karma]: TypeError: sourceMap.originalPositionFor is not a function
    at getMapping (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/getMapping.js:27:26)
    at getMappingResolved (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:204:46)
    at remapBranch (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/remapBranch.js:14:19)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:214:44
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addFileCoverage (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:210:42)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:268:14
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:266:24)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/remap.js:48:13
    at Array.forEach (<anonymous>)
    at Reporter.remap (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/remap.js:47:16)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/karma/reporter.js:38:42
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma/lib/browser_collection.js:93:21)
    at Reporter.create.onRunComplete (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/karma/reporter.js:26:26)
npm ERR! code ELIFECYCLE
```

**Comment by erikbarke** [comment]
I'm working on a fix in #246, feel free to try it out!

**Comment by baywet** [comment]
I can confirm that 3.0.11 workarounds this final issue and allows us to be back on latest version. Thanks guys!

**Comment by erikbarke** [comment]
Ok, so 3.0.11 works for you @baywet, but not for you @rolandjitsu? My guess is using different versions of npm gives different results now because of the `source-map` dependency in `remap-istanbul`, as described in #240. It would be really helpful if you guys could verify that PR #246 works for both of you!

**Comment by baywet** [comment]
on my local machine node 7.10.0
on the build agent 8.9.1
both work with 3.0.11
the fix you authored seems to be working properly on my machine (pulled your branch, npm i, gulp build, npm link and npm link karma-typescript in my repo, let me know if I missed something)

**Comment by rolandjitsu** [comment]
I'm running on OS X Sierra, node 8.4, npm 5.6. I've been using Yarn to install the packages though. Might be because of that. I've switched to jest for now, but I will try the PR out on some other projects where I still use karma.

**Comment by erikbarke** [comment]
@TimothyDespair, the PR #246 uses `remap-istanbul@0.10.1`, does that branch work for you if you install it like baywet describes earlier in this thread?

**Comment by TimothyDespair** [comment]
@erikbarke Just gave it a shot. Seems to be working!

**Comment by erikbarke** [comment]
Awsesome guys, thanks!!
