### PR TITLE
Add support for resolveJsonModule

### LINKED ISSUE #291: Support TS flag resolveJsonModule
In TS 2.9, a compiler flag [resolveJsonModule](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule) was added. Using this in my TS code, I get the following exception with karma-typescript:

Code:
```ts
import data from '../package.json';
```

Output:
```
<timestamp>:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.0.3
<timestamp>:ERROR [compiler.karma-typescript]: src/test(1,8): error TS1192: Module '"<abs folder dir>/package"' has no default export.
```

### PR DESCRIPTION
**Pull request by vidartf**
Allows for direct imports of json into typescript.

Fixes #291.

TODO: Typescript will automatically resolve typings of the imported json (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule). How do I add a test to ensure that TS complains if I use the imported data incorrectly?

### CODE REVIEW

**Comment by erikbarke** [comment]
Hey @vidartf, thanks!!

Some of the ci tests fail on both Travis and Appveyor with these errors:

```bash
Can't find ./browser/algorithms.json [C:/projects/karma-typescript/tests/integration-latest/node_modules/browserify-sign/browser/algorithms.json] (required by C:/projects/karma-typescript/tests/integration-latest/node_modules/browserify-sign/algos.js)

...

Can't find constants [C:/projects/karma-typescript/tests/integration-latest/node_modules/constants-browserify/constants.json] (required by C:/projects/karma-typescript/tests/integration-latest/src/node/core/core-module-tester.ts)

```

Does this work on your end?

**Comment by vidartf** [comment]
@erikbarke I get various errors when installing from master. E.g. today with node 10.11.0 and npm 6.4.1 I get
<details><summary><code>Error: Unable to resolve module [rgb-color]</code></summary>
<pre>
> tests-integration-latest@3.0.13 dev:ci < repo-root >\tests\integration-latest
> gulp dev:ci --cwd . && karma start --browsers ChromeHeadless --single-run

[15:20:34] Using gulpfile < repo-root >\gulpfile.js
[15:20:34] Starting 'clean'...
[15:20:34] Starting 'copy'...
[15:20:34] Finished 'clean' after 28 ms
[15:20:35] Finished 'copy' after 262 ms
[15:20:35] Starting 'dev:ci'...
[15:20:35] Finished 'dev:ci' after 51 µs
10 2018 15:20:42.178:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.1.1
10 2018 15:20:56.527:INFO [compiler.karma-typescript]: Compiled 2091 files in 13409 ms.
10 2018 15:21:14.226:ERROR [karma]: Error: Unable to resolve module [rgb-color] from [< repo-root >/tests/integration-latest/src/bundling/bower/bower-tester.js]
{
  "basedir": "< repo-root >/tests/integration-latest",
  "extensions": [
    ".js",
    ".json",
    ".ts",
    ".tsx"
  ],
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "< repo-root >\\node_modules\\assert\\assert.js",
    "buffer": "< repo-root >\\node_modules\\buffer\\index.js",
    "child_process": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "cluster": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "console": "< repo-root >\\node_modules\\console-browserify\\index.js",
    "constants": "< repo-root >\\node_modules\\constants-browserify\\constants.json",
    "crypto": "< repo-root >\\node_modules\\crypto-browserify\\index.js",
    "dgram": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "dns": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "domain": "< repo-root >\\node_modules\\domain-browser\\source\\index.js",
    "events": "< repo-root >\\node_modules\\events\\events.js",
    "fs": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "http": "< repo-root >\\node_modules\\stream-http\\index.js",
    "https": "< repo-root >\\node_modules\\https-browserify\\index.js",
    "module": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "net": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "os": "< repo-root >\\node_modules\\os-browserify\\browser.js",
    "path": "< repo-root >\\node_modules\\path-browserify\\index.js",
    "punycode": "< repo-root >\\node_modules\\punycode\\punycode.js",
    "querystring": "< repo-root >\\node_modules\\querystring-es3\\index.js",
    "readline": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "repl": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "stream": "< repo-root >\\node_modules\\stream-browserify\\index.js",
    "_stream_duplex": "< repo-root >\\node_modules\\readable-stream\\duplex.js",
    "_stream_passthrough": "< repo-root >\\node_modules\\readable-stream\\passthrough.js",
    "_stream_readable": "< repo-root >\\node_modules\\readable-stream\\readable.js",
    "_stream_transform": "< repo-root >\\node_modules\\readable-stream\\transform.js",
    "_stream_writable": "< repo-root >\\node_modules\\readable-stream\\writable.js",
    "string_decoder": "< repo-root >\\node_modules\\string_decoder\\lib\\string_decoder.js",
    "sys": "< repo-root >\\node_modules\\util\\util.js",
    "timers": "< repo-root >\\node_modules\\timers-browserify\\main.js",
    "tls": "< repo-root >\\dist\\bundler\\resolve\\empty.js",
    "tty": "< repo-root >\\node_modules\\tty-browserify\\index.js",
    "url": "< repo-root >\\node_modules\\url\\url.js",
    "util": "< repo-root >\\node_modules\\util\\util.js",
    "vm": "< repo-root >\\node_modules\\vm-browserify\\index.js",
    "zlib": "< repo-root >\\node_modules\\browserify-zlib\\lib\\index.js",
    "_process": "< repo-root >\\node_modules\\process\\browser.js"
  },
  "filename": "",
  "paths": []
}
Error: Cannot find module 'rgb-color' from 'C:/dev/karma-typescript/tests/integration-latest/src/bundling/bower'
    at < repo-root >\dist\bundler\resolve\resolver.js:178:27
    at < repo-root >\node_modules\browser-resolve\index.js:265:24
    at < repo-root >\node_modules\resolve\lib\async.js:46:14
    at process (< repo-root >\node_modules\resolve\lib\async.js:173:43)
    at ondir (< repo-root >\node_modules\resolve\lib\async.js:188:17)
    at load (< repo-root >\node_modules\resolve\lib\async.js:69:43)
    at onex (< repo-root >\node_modules\resolve\lib\async.js:92:31)
    at < repo-root >\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:154:21)
</pre>
</details>

If I delete the bower test it completes without errors. If I do the same for the branch of this PR, the same happens.

**Comment by vidartf** [comment]
Regarding the failures you mention, I've seen the "constants" one before (see #291), but not the "algorithms" one. The one with "algorithms" might actually be a significant failure though since it involves a JSON being required. But again, I cannot reproduce it.

**Comment by erikbarke** [comment]
I've found (but not solved) what's causing the `[rgb-color]` issue and others, it's tracked in #294!

**Comment by erikbarke** [comment]
If you checkout the branch in #295, does it run on your end with your fixes? After cloning you should be able to run:

```bash
npm run setup
npm run ci
```

I have only tested this with `npm`  v6.4.1 and `node` v8.12.0 and v10.12.0 🤔

**Comment by vidartf** [comment]
@erikbarke Thanks, the CI tests run locally now, and I see that CI passed. The only thing remaining for me then is if you have any input on the TODO note in the top comment. I.e. how to test for an expected failure.

**Comment by vidartf** [comment]
Oh, I still see one error locally: `"message": "Uncaught Error: Can't find ./browser/algorithms.json`, which might actually be relevant to the PR.

**Comment by erikbarke** [comment]
Have you made any progress on this one? 4.0.0 is in beta on npm now and I would like to include this feature in the 4.0.0 release, if possible.

**Comment by vidartf** [comment]
I still need to add a test for checking that the compiler actually gives errors if I use the imported JSON incorrectly. If you could give some pointers for how to check for such an expected compiler error, I could try to get this finished up.

**Comment by erikbarke** [comment]
In that case I think this new feature is good to go: it has a new test describing the added logic and the old tests still pass, that's good enough, merged! Thanks ☺️

**Comment by erikbarke** [comment]
Hey @vidartf, I've reverted your change in `src/bundler/bundle-item.ts` (924fd3402d7c855d088c0ccd8b550beea146795e) since testing for `json` in that regexp broke stuff as detailed in #312.

The integration test you added for `resolveJsonModule` runs without the `json` regexp, does your project(s) run ok with `karma-typescript@4.0.0-beta.3`?

**Comment by vidartf** [comment]
@erikbarke This PR never really had a test for any *expected compilation errors* if this feature was enabled, which honestly is one of the main features of the `resolveJsonModule` compiler flag. As such, I wouldn't rely on the unit tests passing as a way of checking if this works.

Any help on how to check for expected compilation errors could help get this cleaned up.
