### ISSUE TITLE
Compiler error: Argument of type not assignable to parameter

### ISSUE THREAD

**Issue by afterbangx** [monounity/karma-typescript#145]
I'm really not sure what caused this error to start as I wasn't the one that first noticed it. I have a coworker that was doing some work on a feature branch and she asked me to look into why her build is failing. Seems to be a `karma-typescript` compiler error but she didn't make any changes that should of caused this to suddenly start failing. The really weird part is ALL of the tests seem to be passing successfully. There are just a ton of console errors like this one causing the build to fail. Ever seen anything like this before?

```
30 06 2017 11:14:41.466:ERROR [compiler.karma-typescript]: App/Customers/Customer/Billing/PaymentsHistory/RecordCreditCardPaymentController.controller.ts(172,58): error TS2345: Argument of type 'typeof RecordCreditCardPaymentController' is not assignable to parameter of type 'Injectable<IControllerConstructor>'.
  Type 'typeof RecordCreditCardPaymentController' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
    Property 'push' is missing in type 'typeof RecordCreditCardPaymentController'.
```

We were on 3.0.3 but I updated to 3.0.4 and still see the error. Any tips on what I should be looking for?

**Comment by erikbarke** [comment]
Hey @afterbangx, has anything else changed in your environment? Are you locked on the Typescript version, typings versions, third party libs etc?

I'm constantly fixing these kinds of warnings on the build servers for this project because, for example, the latest version of Typescript is installed on every run and what worked in version X might break in version Y 😃

**Comment by chrismbarr** [comment]
Perhaps it's due to requiring `"typescript": "latest"` instead of a specific version.
https://github.com/monounity/karma-typescript/blob/master/package.json#L133

Right now 2.4.1 is latest, which now has some stricter rules around typedefs.  I think this could be fixed if this was removed or replaced with a specific known working TS version instead of just getting the latest version whenever it's released.

**Comment by afterbangx** [comment]
Yeah, it was working on `3.0.3` with `typescript 2.3.4`. I think our problem is because we are still using the angular 1.5 type definitions. I found a similar issue to this one posted there that says it's been fixed in the 1.6.x type defs but we can't upgrade without a significant amount of refactoring.  Can we lock `3.0.3` to `typescript 2.3.4`? That way we can continue to use this package until we can upgrade to the latest angular type defs and ts 2.4.

**Comment by erikbarke** [comment]
Typescript is only a dev dependency for karma-typescript used for building the plain javascript distribution version, you can use any version of Typescript you need from 1.6.2 and up to the latest 2.x series!

I just verified this by running `npm i karma-typescript` in an empty folder and npm didn't install any Typescript version in the node_modules folder.

Also, the build servers run [integration tests](https://travis-ci.org/monounity/karma-typescript/builds/249772358) for Typescript that are locked on 1.6.2, 1.8.10 and latest.

What Typescript version have you specified in your package.json? Do you have a global installation of Typescript that somehow gets upgraded to the latest version by another project?

**Comment by afterbangx** [comment]
Hmm, that's interesting. We are on `2.3.4` but it keeps installing and compiling with `2.4.1` for some reason. I'll play with it some more tomorrow morning and let you know how it goes.

**Comment by afterbangx** [comment]
Hey @erikbarke I was able to get it working by locking down typescript to `2.3.4` in our project. We had it set to always install the latest minor version which is where the errors were coming from. Thanks for the tip. Closing this issue.

**Comment by chrismbarr** [comment]
A workaround for this would bet to set `"skipLibCheck": true` in `tsconfig.json`.  This is a new compiler flag available in TS 2.4+
